version: ""

formatter: markdown table

name: terraform-aws-ecs-fargate-codepipeline

content: |-
  # terraform-aws-ecs-fargate-codepipeline
  
  GitHub: [StratusGrid/terraform-aws-ecs-fargate-codepipeline](https://github.com/StratusGrid/terraform-aws-ecs-fargate-codepipeline)

  This module creates an end-to-end fargate cluster with a single task (but can be multiple containers in the task), a CodeDeploy application deployment configuration, a CodePipeline to wrap around it, and all relevant iam roles etc.

  ### NOTE:

  If you get a Cycle: Error: on destroy, go remove the LB target group that is getting changes first.
  ```shell
  terraform apply -target aws_lb_target_group.data_hub_web_http
  ```

  If you get errors about the artifact.zip files, you must create the resources which get pulled into the file first, by targeting the iam roles and target groups.

  ```shell
  terraform apply -target aws_lb_target group.<blue_target_group> -target aws_lb_target_group.<green_target_group>
  terraform apply -target module.<ecs_iam_role1> -target module.<ecs_iam_role2>
  ```

  ### Example Usage:
  Create a cluster with a single service, mapped to a single task, which has a single container:
  ```hcl
  {{ include "examples/Cluster-with-single-service/example1.tfnot" }}
  ```
  ---
  Valid combinations of cpu/memory in task definition is found [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html)
  ```hcl
  {{ include "examples/variable-cpu-memory-combinations/example1.tfnot" }}
  ```
  ---

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  ## Contributors
  - Chris Hurst [GenesisChris](https://github.com/GenesisChris)
  - Ivan Casco [ivancasco-sg](https://github.com/ivancasco-sg)
  - Jason Drouhard [jason-drouhard](https://github.com/jason-drouhard)
  - Matt Barlow [mattbarlow-sg](https://github.com/mattbarlow-sg)
  - Jonathan Woods [stratusgrid-jw](https://github.com/stratusgrid-jw)
  - Angel Lopez [angellopez-sg](https://github.com/angellopez-sg)

  <span style="color:red">NOTE:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace